name: Validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091d690fe712d2e5fd0da0441a35f29e6a85c2 # v7.0.0
      - uses: actions/setup-python@ece7cd6a34d7c42a2e5f8a5746afb5e36f65b0cf # v6.3.0
        with:
          python-version: "3.13"
          cache: pip
      - run: python -m pip install -r requirements-test.txt
      - run: ruff check .
      - run: pytest

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091d690fe712d2e5fd0da0441a35f29e6a85c2 # v7.0.0
      - uses: home-assistant/actions/hassfest@f4ca62a9a6333d53516579562bd9e7d81b0372b4

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091d690fe712d2e5fd0da0441a35f29e6a85c2 # v7.0.0
      - uses: hacs/action@d556e3ca686adefed1a697dec8b8f3a639b42a95 # 22.5.0
        with:
          category: integration
          ignore: brands
